### ISSUE TITLE
[1pt] Implement the startup actions(group task)

### ISSUE THREAD

**Issue by TuyishimireEric** [Aquinasmoriasi/catalog-of-my-things#2]
- Create a main.rb file that will serve as your console app entry-point.
- Implement startup actions:
  - Present the user with a list of options to perform.
  - Let users choose an option.
  - If needed, ask for parameters for the option.
  - Have a way to quit the app.

**Comment by Aquinasmoriasi** [comment]
- This [pull request](https://github.com/Aquinasmoriasi/catalog-of-my-things/pull/32) resolves this issue.
