### ISSUE TITLE
[3pt] Create a Label class

### ISSUE THREAD

**Issue by TuyishimireEric** [Aquinasmoriasi/catalog-of-my-things#5]
- Create a Label class with an association to the Item class (in a separate .rb file).
- All Label class properties visible in the diagram should be defined and set up in the constructor method.

- The following options should be available: 
    - List all books
    - List all labels (e.g. 'Gift', 'New') 
    - Add a book

**Comment by Aquinasmoriasi** [comment]
This [pull request](https://github.com/Aquinasmoriasi/catalog-of-my-things/pull/26) closes this issue.
